spring.application.name=loot
server.port=9001

spring.main.lazy-initialization=true

management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

